version: '3.5'
services:
  backend:
    image: dnnd/keep4u-backend
    ports:
    - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - keep4u-backend
  mongo:
    image: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - keep4u-backend
networks:
  keep4u-backend:
    name: keep4u-backend
