openapi: 3.0.0
info:
  version: "0.0.1"
  title: keep4u rest api
  description: keep4u backend rest api
paths:
  /boards:
    $ref: 'boards.yml'
  /boards/{board_id}:
    $ref: 'boards_id.yml'
  /boards/{board_id}/collaborators:
    $ref: 'boards_id_collaborators.yml'
  /boards/{board_id}/notes:
    $ref: 'notes.yml'
  /notes/{note_id}:
    $ref: 'notes_id.yml'
  /attachments:
    $ref: 'attachments.yml'
  /attachments/{attachment_id}:
    $ref: 'attachments_id.yml'
  /search/notes:
    $ref: 'search_notes.yml'



components:
  parameters:
    board_id:
      $ref: 'parameters.yml#/BoardID'
    note_id:
      $ref: 'parameters.yml#/NoteID'
    user_id:
      $ref: 'parameters.yml#/UserID'
    attachment_id:
      $ref: 'parameters.yml#/AttachmentID'
  schemas:
    Board:
      $ref: 'schemas.yml#/Board'
    Collaborators:
      $ref: 'schemas.yml#/Collaborators'
    Note:
      $ref: 'schemas.yml#/Note'
    Boards:
      $ref: 'schemas.yml#/Boards'
    NoteUpdate:
      $ref: 'schemas.yml#/NoteUpdate'
    BoardUpdate:
      $ref: 'schemas.yml#/BoardUpdate'
    Notes:
      $ref: 'schemas.yml#/Notes'
    Attachment:
      $ref: 'schemas.yml#/Attachment'
    Attachments:
      $ref: 'schemas.yml#/Attachments'
    Error:
      $ref: 'schemas.yml#/Error'

servers:
- description: Development server
  url: http://188.246.233.13:8080/
