NoteID:
  schema:
    type: string
  in: path
  name: note_id
  required: true
  description: UUID of note

BoardID:
  schema:
    type: string
  in: path
  name: board_id
  required: true
  description: UUID of board

AttachmentID:
  schema:
    type: string
  in: path
  name: attachment_id
  required: true
  description: UUID of attachment
