NoteID:
  schema:
    type: string
  in: path
  name: note_id
  required: true
  description: UUID of note

BoardID:
  schema:
    type: string
  in: path
  name: board_id
  required: true
  description: UUID of board

OwnerID:
  schema:
    type: string
  in: query
  name: owner_id
  required: true
  description: Google ClientID token

UserID:
  schema:
    type: string
  in: header
  name: Authorization
  required: true
  description: Google ClientID token

AttachmentID:
  schema:
    type: string
  in: path
  name: attachment_id
  required: true
  description: UUID of attachment
